### ISSUE TITLE
Refreshing portfolio page breaks the app

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/ui#1383]
I'm using Chrome Version 114.0.5735.133 (Official Build) (x86_64).

<img width="1920" alt="Screenshot 2023-06-19 at 10 49 52" src="https://github.com/zeitgeistpm/ui/assets/49552287/6d403dd1-fade-4e7e-9bdf-6b04a62d2eaa">

Console output:

```
lockdown-install.js:1 Removing intrinsics.JSON.rawJSON
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.JSON.isRawJSON
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.toReversed
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.toSorted
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.toSpliced
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.with
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.toReversed
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSorted
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSpliced
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayBufferPrototype%.transferToFixedLength
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayBufferPrototype%.detached
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%StringPrototype%.isWellFormed
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%StringPrototype%.toWellFormed
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%RegExpPrototype%.unicodeSets
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.toReversed
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.toSorted
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.with
visitProperties @ lockdown-install.js:1
_app-3c8fb2362ef4fd25.js:667 @zeitgeistpm/sdk: connecting to indexer: https://processor.rpc-0.zeitgeist.pm/graphql
4293.f922429086ebb210.js:1 @polkadot/api has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	cjs 9.14.2	<unknown>
	esm 9.14.2	node_modules/@polkadot/api/
o @ 4293.f922429086ebb210.js:1
_app-3c8fb2362ef4fd25.js:667 @zeitgeistpm/sdk: connecting to rpc: wss://main.rpc.zeitgeist.pm/ws,wss://zeitgeist-rpc.dwellir.com,wss://zeitgeist.api.onfinality.io/public-ws
_app-3c8fb2362ef4fd25.js:667 @zeitgeistpm/sdk: connected to indexer, response time 159ms
_app-3c8fb2362ef4fd25.js:270 2023-06-19 10:49:41        API/INIT: RPC methods not decorated: mmr_root, mmr_verifyProof, mmr_verifyProofStateless
g @ _app-3c8fb2362ef4fd25.js:270
_app-3c8fb2362ef4fd25.js:270 2023-06-19 10:49:41        API/INIT: polkadot/9420: Not decorating runtime apis without matching versions: BeefyApi/2 (1 known), Metadata/2 (1 known), MmrApi/2 (1 known), ParachainHost/4 (1/2/3 known), TransactionPaymentApi/4 (1/2/3 known)
g @ _app-3c8fb2362ef4fd25.js:270
_app-3c8fb2362ef4fd25.js:270 2023-06-19 10:49:41        API/INIT: polkadot/9420: Not decorating unknown runtime apis: 0x18ef58a3b67ba770/1
g @ _app-3c8fb2362ef4fd25.js:270
_app-3c8fb2362ef4fd25.js:667 @zeitgeistpm/sdk: connected to node rpc
_app-3c8fb2362ef4fd25.js:270 2023-06-19 10:49:41        API/INIT: RPC methods not decorated: mmr_root, mmr_verifyProof, mmr_verifyProofStateless
g @ _app-3c8fb2362ef4fd25.js:270
_app-3c8fb2362ef4fd25.js:270 2023-06-19 10:49:41        API/INIT: kusama/9420: Not decorating runtime apis without matching versions: BeefyApi/2 (1 known), Metadata/2 (1 known), MmrApi/2 (1 known), ParachainHost/4 (1/2/3 known), TransactionPaymentApi/4 (1/2/3 known)
g @ _app-3c8fb2362ef4fd25.js:270
_app-3c8fb2362ef4fd25.js:270 2023-06-19 10:49:41        API/INIT: kusama/9420: Not decorating unknown runtime apis: 0x18ef58a3b67ba770/1
g @ _app-3c8fb2362ef4fd25.js:270
framework-ce84985cd166733a.js:9 Error: [DecimalError] Invalid argument: null
    at new i (_app-3c8fb2362ef4fd25.js:673:28574)
    at C.minus.C.sub (_app-3c8fb2362ef4fd25.js:673:10703)
    at tt ([address]-a0e369e6578e409f.js:1:43628)
    at [address]-a0e369e6578e409f.js:1:42406
    at Object.aQ [as useMemo] (framework-ce84985cd166733a.js:9:65290)
    at n.useMemo (framework-ce84985cd166733a.js:25:5986)
    at e7 ([address]-a0e369e6578e409f.js:1:39344)
    at td ([address]-a0e369e6578e409f.js:1:44368)
    at ab (framework-ce84985cd166733a.js:9:60917)
    at ud (framework-ce84985cd166733a.js:9:72803)
a5 @ framework-ce84985cd166733a.js:9
main-dc36586e01a8d0ae.js:1 Error: [DecimalError] Invalid argument: null
    at new i (_app-3c8fb2362ef4fd25.js:673:28574)
    at C.minus.C.sub (_app-3c8fb2362ef4fd25.js:673:10703)
    at tt ([address]-a0e369e6578e409f.js:1:43628)
    at [address]-a0e369e6578e409f.js:1:42406
    at Object.aQ [as useMemo] (framework-ce84985cd166733a.js:9:65290)
    at n.useMemo (framework-ce84985cd166733a.js:25:5986)
    at e7 ([address]-a0e369e6578e409f.js:1:39344)
    at td ([address]-a0e369e6578e409f.js:1:44368)
    at ab (framework-ce84985cd166733a.js:9:60917)
    at ud (framework-ce84985cd166733a.js:9:72803)
$ @ main-dc36586e01a8d0ae.js:1
main-dc36586e01a8d0ae.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
$ @ main-dc36586e01a8d0ae.js:1
lockdown-install.js:1 Removing intrinsics.JSON.rawJSON
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.JSON.isRawJSON
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.toReversed
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.toSorted
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.toSpliced
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.with
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.toReversed
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSorted
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSpliced
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayBufferPrototype%.transferToFixedLength
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayBufferPrototype%.detached
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%StringPrototype%.isWellFormed
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%StringPrototype%.toWellFormed
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%RegExpPrototype%.unicodeSets
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.toReversed
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.toSorted
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.with
visitProperties @ lockdown-install.js:1
inpage.js:1 MetaMask: Connected to chain with ID "0x505".
 Removing intrinsics.JSON.rawJSON
visitProperties @ lockdown-install.js:1
 Removing intrinsics.JSON.isRawJSON
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.toReversed
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.toSorted
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.toSpliced
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.with
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.@@unscopables.toReversed
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSorted
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSpliced
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayBufferPrototype%.transferToFixedLength
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayBufferPrototype%.detached
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%StringPrototype%.isWellFormed
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%StringPrototype%.toWellFormed
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%RegExpPrototype%.unicodeSets
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%TypedArrayPrototype%.toReversed
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%TypedArrayPrototype%.toSorted
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%TypedArrayPrototype%.with
visitProperties @ lockdown-install.js:1
 Removing intrinsics.JSON.rawJSON
visitProperties @ chrome-extension://n…ckdown-install.js:1
 Removing intrinsics.JSON.isRawJSON
visitProperties @ chrome-extension://n…ckdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.toReversed
visitProperties @ chrome-extension://n…ckdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.toSorted
visitProperties @ chrome-extension://n…ckdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.toSpliced
visitProperties @ chrome-extension://n…ckdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.with
visitProperties @ chrome-extension://n…ckdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.@@unscopables.toReversed
visitProperties @ chrome-extension://n…ckdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSorted
visitProperties @ chrome-extension://n…ckdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSpliced
visitProperties @ chrome-extension://n…ckdown-install.js:1
 Removing intrinsics.%ArrayBufferPrototype%.transferToFixedLength
visitProperties @ chrome-extension://n…ckdown-install.js:1
 Removing intrinsics.%ArrayBufferPrototype%.detached
visitProperties @ chrome-extension://n…ckdown-install.js:1
 Removing intrinsics.%StringPrototype%.isWellFormed
visitProperties @ chrome-extension://n…ckdown-install.js:1
 Removing intrinsics.%StringPrototype%.toWellFormed
visitProperties @ chrome-extension://n…ckdown-install.js:1
 Removing intrinsics.%RegExpPrototype%.unicodeSets
visitProperties @ chrome-extension://n…ckdown-install.js:1
 Removing intrinsics.%TypedArrayPrototype%.toReversed
visitProperties @ chrome-extension://n…ckdown-install.js:1
 Removing intrinsics.%TypedArrayPrototype%.toSorted
visitProperties @ chrome-extension://n…ckdown-install.js:1
 Removing intrinsics.%TypedArrayPrototype%.with
visitProperties @ chrome-extension://n…ckdown-install.js:1
 Removing intrinsics.JSON.rawJSON
visitProperties @ lockdown-install.js:1
 Removing intrinsics.JSON.isRawJSON
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.toReversed
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.toSorted
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.toSpliced
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.with
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.@@unscopables.toReversed
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSorted
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSpliced
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayBufferPrototype%.transferToFixedLength
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayBufferPrototype%.detached
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%StringPrototype%.isWellFormed
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%StringPrototype%.toWellFormed
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%RegExpPrototype%.unicodeSets
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%TypedArrayPrototype%.toReversed
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%TypedArrayPrototype%.toSorted
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%TypedArrayPrototype%.with
visitProperties @ lockdown-install.js:1
 Removing intrinsics.JSON.rawJSON
visitProperties @ lockdown-install.js:1
 Removing intrinsics.JSON.isRawJSON
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.toReversed
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.toSorted
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.toSpliced
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.with
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.@@unscopables.toReversed
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSorted
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSpliced
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayBufferPrototype%.transferToFixedLength
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayBufferPrototype%.detached
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%StringPrototype%.isWellFormed
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%StringPrototype%.toWellFormed
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%RegExpPrototype%.unicodeSets
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%TypedArrayPrototype%.toReversed
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%TypedArrayPrototype%.toSorted
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%TypedArrayPrototype%.with
visitProperties @ lockdown-install.js:1
 Removing intrinsics.JSON.rawJSON
visitProperties @ lockdown-install.js:1
 Removing intrinsics.JSON.isRawJSON
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.toReversed
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.toSorted
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.toSpliced
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.with
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.@@unscopables.toReversed
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSorted
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSpliced
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayBufferPrototype%.transferToFixedLength
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%ArrayBufferPrototype%.detached
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%StringPrototype%.isWellFormed
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%StringPrototype%.toWellFormed
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%RegExpPrototype%.unicodeSets
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%TypedArrayPrototype%.toReversed
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%TypedArrayPrototype%.toSorted
visitProperties @ lockdown-install.js:1
 Removing intrinsics.%TypedArrayPrototype%.with
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.JSON.rawJSON
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.JSON.isRawJSON
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.toReversed
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.toSorted
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.toSpliced
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.with
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.toReversed
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSorted
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSpliced
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayBufferPrototype%.transferToFixedLength
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%ArrayBufferPrototype%.detached
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%StringPrototype%.isWellFormed
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%StringPrototype%.toWellFormed
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%RegExpPrototype%.unicodeSets
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.toReversed
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.toSorted
visitProperties @ lockdown-install.js:1
lockdown-install.js:1 Removing intrinsics.%TypedArrayPrototype%.with
```

**Comment by Robiquet** [comment]
I've noticed this too intermittently.  We should prioritise strict null checks on this page
