### ISSUE TITLE
Investigate Vercel server function errors

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#645]
Looks like we are on track to use around 50% of our allowance on errors alone.

The error can be found on the functions tab: 
```
2023-01-31T16:08:24.334Z	86cf5b2a-7ffc-4001-9a6e-3046d108d6e1	ERROR	Error: ENOENT: no such file or directory, open '/var/task/public/carousel/intro_zeitgeist_avatar.png'
    at Object.openSync (node:fs:600:3)
    at syncFileToBuffer (/var/task/node_modules/plaiceholder/dist/index.js:84081:47)
    at imageSize (/var/task/node_modules/plaiceholder/dist/index.js:84120:24)
    at getImageSize (/var/task/node_modules/plaiceholder/dist/index.js:84152:7)
    at loadImage (/var/task/node_modules/plaiceholder/dist/index.js:84205:21)
    at getImage (/var/task/node_modules/plaiceholder/dist/index.js:84272:13)
    at getPlaiceholder (/var/task/node_modules/plaiceholder/dist/index.js:84350:13)
    at getStaticProps (/var/task/.next/server/pages/index.js:65:71)
    at Object.renderToHTML (/var/task/node_modules/next/dist/server/render.js:384:26)
    at async doRender (/var/task/node_modules/next/dist/server/base-server.js:701:34) {
  errno: -2,
  syscall: 'open',
  path: '/var/task/public/carousel/intro_zeitgeist_avatar.png',
  page: '/'
}
RequestId: 86cf5b2a-7ffc-4001-9a6e-3046d108d6e1 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```
Looks like it could have something to do with the banner image sizing or placeholder generation.

**Comment by Robiquet** [comment]
I deleted the carousel png but now it's erroring on `sports.png`

**Comment by Robiquet** [comment]
https://github.com/zeitgeistpm/ui/pull/798

**Comment by Robiquet** [comment]
Fixed
