### ISSUE TITLE
SyntaxError: "undefined" is not valid JSON  & TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by ltfschoen** [zeitgeistpm/ui#686]
i cloned the latest commit 7fc7770f9f2e14f36a614d6d9fdfa973bf358aeb from the branch 'staging' of this repo on an ubuntu 22.04 machine, then install node v19.6.0 and yarn 3.2.2, then following instructions in the readme by installing dependencies with `yarn install`.

but when i ran the server and when to http://localhost:3000 i got the following errors:

```
$ yarn dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - You have enabled experimental feature (scrollRestoration) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

event - compiled client and server successfully in 51s (6292 modules)
wait  - compiling...
event - compiled successfully in 5.4s (6099 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 3.3s (6331 modules)
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	cjs 10.3.1	node_modules/@polkadot/util/cjs
	esm 10.3.1	node_modules/@polkadot/util/
@polkadot/util-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	cjs 10.3.1	node_modules/@polkadot/util-crypto/cjs
	esm 10.3.1	node_modules/@polkadot/util-crypto/
@polkadot/wasm-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	cjs 6.4.1	node_modules/@polkadot/wasm-crypto/cjs
	esm 6.4.1	node_modules/@polkadot/wasm-crypto/
@polkadot/wasm-bridge has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	cjs 6.4.1	node_modules/@polkadot/wasm-bridge/cjs
	esm 6.4.1	node_modules/@polkadot/wasm-bridge/
@polkadot/wasm-crypto-wasm has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	cjs 6.4.1	node_modules/@polkadot/wasm-crypto-wasm/cjs
	esm 6.4.1	node_modules/@polkadot/wasm-crypto-wasm/
@polkadot/wasm-util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	cjs 6.4.1	node_modules/@polkadot/wasm-util/cjs
	esm 6.4.1	node_modules/@polkadot/wasm-util/
@polkadot/keyring has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	cjs 10.3.1	node_modules/@polkadot/keyring/cjs
	esm 10.3.1	node_modules/@polkadot/keyring/
SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at getMarketIdsFromEnvVar (webpack-internal:///./lib/gql/featured-markets.ts:19:27)
    at eval (webpack-internal:///./lib/gql/featured-markets.ts:28:19)
wait  - compiling /_error (client and server)...
error - TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (~/ui/node_modules/next/dist/compiled/node-fetch/index.js:1:63531)
    at ~/ui/node_modules/next/dist/compiled/node-fetch/index.js:1:65062
    at new Promise (<anonymous>)
    at fetch (~/ui/node_modules/next/dist/compiled/node-fetch/index.js:1:64996)
    at fetch (~/ui/node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
    at ~/ui/node_modules/graphql-request/dist/index.js:163:42
    at step (~/ui/node_modules/graphql-request/dist/index.js:63:23)
    at Object.next (~/ui/node_modules/graphql-request/dist/index.js:44:53)
    at ~/ui/node_modules/graphql-request/dist/index.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (~/ui/node_modules/graphql-request/dist/index.js:34:12)
    at post (~/ui/node_modules/graphql-request/dist/index.js:157:12)
    at ~/ui/node_modules/graphql-request/dist/index.js:316:42
    at step (~/ui/node_modules/graphql-request/dist/index.js:63:23)
    at Object.next (~/ui/node_modules/graphql-request/dist/index.js:44:53)
    at ~/ui/node_modules/graphql-request/dist/index.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (~/ui/node_modules/graphql-request/dist/index.js:34:12)
    at makeRequest (~/ui/node_modules/graphql-request/dist/index.js:309:12)
    at GraphQLClient.<anonymous> (~/ui/node_modules/graphql-request/dist/index.js:224:46)
    at step (~/ui/node_modules/graphql-request/dist/index.js:63:23)
    at Object.next (~/ui/node_modules/graphql-request/dist/index.js:44:53)
    at ~/ui/node_modules/graphql-request/dist/index.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (~/ui/node_modules/graphql-request/dist/index.js:34:12)
    at GraphQLClient.request (~/ui/node_modules/graphql-request/dist/index.js:216:16)
    at getTrendingMarkets (webpack-internal:///./lib/gql/trending-markets.ts:76:35)
    at getStaticProps (webpack-internal:///./pages/index.tsx:54:77)
    at Object.renderToHTML (~/ui/node_modules/next/dist/server/render.js:385:26)
    at async doRender (~/ui/node_modules/next/dist/server/base-server.js:720:34)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (~/ui/node_modules/next/dist/server/base-server.js:837:28)
    at async ~/ui/node_modules/next/dist/server/response-cache/index.js:83:36 {
  page: '/'
}
```

**Comment by ltfschoen** [comment]
my mistake, i didn't fully follow the readme instructions, i overlooked copying the example env file, it worked after i ran 
```
cp .env.example .env.local
```
